const ADD_FAVORITE = 'ADD_FAVORITE';
const REMOVE_FAVORITE = 'REMOVE_FAVORITE';
const FILTER_CARDS = 'FILTER_CARDS';
const ORDER_CARDS = 'ORDER_CARDS'

module.exports = {
    ADD_FAVORITE,
    REMOVE_FAVORITE,
    FILTER_CARDS,
    ORDER_CARDS,
}